apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx 
  namespace: default
  labels:
    app: nginx 
spec:
  selector:
    matchLabels:
      app: nginx 
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
      - name: nginx 
        image: hello-world:latest 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name:  nginx
  namespace: default
spec:
  selector:
    app:  nginx
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
